Repository LArSoft/larcorealg, pull requests merged in 2020-02, with the labels that each got.

#2 Add two github actions to move new pull requests or issues to the LArSoft pull requests project
  .github/workflows/opened-issues-triage.yml
  .github/workflows/opened-pulls-triage.yml
Labels: L1-approved, code-checks-approved, new-package-pending, requires-external, signatures-pending, tests-started

#3 Clean up and make geometry system threadsafe
  larcorealg/GeoAlgo/CMakeLists.txt
  larcorealg/Geometry/AuxDetChannelMapAlg.cxx
  larcorealg/Geometry/AuxDetChannelMapAlg.h
  larcorealg/Geometry/AuxDetGeo.cxx
  larcorealg/Geometry/AuxDetGeoObjectSorter.h
  larcorealg/Geometry/AuxDetGeometryCore.cxx
  larcorealg/Geometry/AuxDetGeometryCore.h
  larcorealg/Geometry/CMakeLists.txt
  larcorealg/Geometry/ChannelMapAlg.cxx
  larcorealg/Geometry/ChannelMapAlg.h
  larcorealg/Geometry/CryostatGeo.cxx
  larcorealg/Geometry/GeoObjectSorter.cxx
  larcorealg/Geometry/GeoObjectSorter.h
  larcorealg/Geometry/GeoObjectSorterStandard.cxx
  larcorealg/Geometry/GeoObjectSorterStandard.h
  larcorealg/Geometry/GeometryBuilder.h
  larcorealg/Geometry/GeometryBuilderStandard.cxx
  larcorealg/Geometry/GeometryBuilderStandard.h
  larcorealg/Geometry/GeometryCore.cxx
  larcorealg/Geometry/GeometryCore.h
  larcorealg/Geometry/GeometryData.h
  larcorealg/Geometry/OpDetGeo.cxx
  larcorealg/Geometry/PlaneGeo.cxx
  larcorealg/Geometry/StandaloneGeometrySetup.cxx
  larcorealg/Geometry/StandaloneGeometrySetup.h
  test/CoreUtils/CMakeLists.txt
  test/Geometry/CMakeLists.txt
  test/Geometry/GeometryTestAlg.cxx
  test/Geometry/geometry_unit_test_base.h
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, requires-external, tests-started

#4 declare project language and update cmake_minimum_required
  CMakeLists.txt
Labels: L1-approved, L2-approved, code-checks-approved, fully-signed, tests-started
